import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = () => {
  useEffect(() => {
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          const userAgent = navigator.userAgent;
          const { latitude, longitude } = position.coords;

          try {
            const response = await fetch("/api/storeInfo", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({ userAgent, latitude, longitude }),
            });

            if (!response.ok) {
              throw new Error("Failed to store data");
            }

            const data = await response.json();
            console.log(data);
          } catch (error) {
            console.error("Error:", error);
          }
        },
        (error) => {
          console.error("Geolocation Error:", error);
        }
      );
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* ... (rest of the original content) ... */}
        <div className={styles.description}>
          <p>Hello World</p>
        </div>
        {/* ... (rest of the original content) ... */}
      </main>
    </>
  );
};

export default Home;
