import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = () => {
  useEffect(() => {
    // Generate or retrieve a unique identifier for the browser or device
    let browserID = localStorage.getItem("browserID");
    if (!browserID) {
      browserID = Math.random().toString(36).substr(2, 9); // This is a simple ID. Consider using a library like `uuid` for more robust IDs.
      localStorage.setItem("browserID", browserID);
    }

    const userAgent = navigator.userAgent;

    // Send data immediately upon page landing
    const sendData = async (data: any) => {
      try {
        const response = await fetch("/api/storeInfo", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ data, browserID }),
        });

        if (!response.ok) {
          throw new Error("Failed to store data");
        }

        const responseData = await response.json();
        console.log(responseData);
      } catch (error) {
        console.error("Error:", error);
      }
    };

    sendData({ event: "pageLanding", userAgent });

    // Try to get geolocation and send data if permission is granted
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const { latitude, longitude } = position.coords;
          sendData({
            event: "geolocationGranted",
            userAgent,
            latitude,
            longitude,
          });
        },
        (error) => {
          console.error("Geolocation Error:", error);
        }
      );
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* ... (rest of the original content) ... */}
        <div className={styles.description}>
          <p>Hello World</p>
        </div>
        {/* ... (rest of the original content) ... */}
      </main>
    </>
  );
};

export default Home;
